// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhowwesvohqhxmfzqfmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFob3d3ZXN2b2hxaHhtZnpxZm1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MDIxNDQsImV4cCI6MjA1ODk3ODE0NH0.oAQkphTfddmiXH3zg_hxeRheMstkLSktP2pEzrpAvz4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);